### ISSUE TITLE
Select CSS framework and UI kit for initial version

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#10]
Which CSS framework and UI kit should we use in MVP version?
- https://flowbite.com/
- https://ui.shadcn.com/
- https://mui.com/
- https://daisyui.com/
- https://www.skeleton.dev/
- https://developer.microsoft.com/en-us/fluentui#/controls/web
- https://shoelace.style/
- https://getbootstrap.com/
- https://preline.co/index.html

**Comment by ParsaGachkar** [comment]
**Daisy** and **Flowbite** both have good theming features 
- https://daisyui.com/docs/themes/ 
- https://flowbite.com/docs/customize/theming/

**Flowbite** has official blazor support https://flowbite.com/docs/getting-started/blazor/
