### ISSUE TITLE
Autofocus should not add tabindex="-1" to element.

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1024]
currently the element that is autofucus, also has tabindex="-1" which should not be like this.

**Comment by pournasserian** [comment]
@TheHadiAhmadi is this issue valid?

**Comment by TheHadiAhmadi** [comment]
Yes, If we use blazor's FocusOnNavigate (or ExterdedFocusOnNavigate Which we had before), It will add tabindex=-1 to the focused element. 
We should consider this issue when we want to add autofocus feature to project.

**Comment by TheHadiAhmadi** [comment]
@pournasserian it can be a comment in the issue related to Adding Autofocus and tabindex order of elements.
