### ISSUE TITLE
Enable Antiforgery

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1029]
In startup we should use `app.UseAntiforgery();` for security reason.

**Comment by ParsaGachkar** [comment]
Based on my understanding and [Microsoft’s documentation](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0) on CSRF and JWT, this might not impact projects that don’t use Cookie authentication. ASP’s Antiforgery Token is typically used in form submissions, not REST APIs. We’re already using JWT for user authorization. I think that ensuring sanitization of our content to prevent JS injection attacks is more important. Let’s keep the discussion going!

**Comment by ParsaGachkar** [comment]
looks like we're already using it https://github.com/fluentcms/FluentCMS/blob/4324adbf269b1a0be0f143ed86badcfdb71fc324/src/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs#L68
