### ISSUE TITLE
In `IBaseEntity`: `Id`, `CreateDate` and `UpdateDate` should be set in repository

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#103]

**Comment by ParsaGachkar** [comment]
this is already handled for IAuditEntities

**Comment by MostafaTech** [comment]
> this is already handled for `IAuditEntities`

I think this issue means that, setting CreateDate and UpdateDate should be placed in repository.
But if we are using domain rich models, they shoud be set in the model itself.
