### ISSUE TITLE
Navigate from one plugin to another plugin is not working

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1107]
Section.razor file doesn't respect pluginDef query parameter

**Comment by pournasserian** [comment]
@TheHadiAhmadi would you mention where we have the issue?

**Comment by TheHadiAhmadi** [comment]
@pournasserian I had issue when I wanted to navigate to create content type page from another plugin.

Render engine was searching for "Create ContentType" type name in the "Content Plugin" 
(After navigate, it won't change currently active plugin)

**Comment by pournasserian** [comment]
> @pournasserian I had issue when I wanted to navigate to create content type page from another plugin.
> 
> Render engine was searching for "Create ContentType" type name in the "Content Plugin" (After navigate, it won't change currently active plugin)

Thanks, since we are redesigning the plugins, I am closing this issue. Don't forget to reopen if we face it later.
