### ISSUE TITLE
(content) We can't navigate to another collection in mobile view

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1190]
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/dea88e12-942a-4830-bb1a-ac63b1e2219e)

![image](https://github.com/fluentcms/FluentCMS/assets/42554876/377c624a-8411-4ccf-b4c0-7cdf5d8baf55)

![image](https://github.com/fluentcms/FluentCMS/assets/42554876/ffb82df1-850d-4b86-89ce-91b415d5240e)

**Comment by pournasserian** [comment]
Closed by #1326
