### ISSUE TITLE
`Page` component and its related components should be deleted  

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1217]

**Comment by TheHadiAhmadi** [comment]
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/bab3c909-62a3-4285-b01b-c11f5a6f7921)

**Comment by pournasserian** [comment]
@TheHadiAhmadi he usage is correct, but we don't have Page concept. Maybe the name should be changed.
