### ISSUE TITLE
Review and complete User Management plugin

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1234]
Required features:

- Show list of users and their roles in table. Fields are: username, first name, last name, email, phone, disable, create date, last login date, login count, roles, email confirmed, phone confirmed, enabled, locked
- Create user: input all fields in UI (we don't have roles, enabled, etc.)
- Update user: input all fields in UI (we don't have roles, enabled, etc.). Also, admin can set password.

For users list, these are good examples:

https://flowbite.com/blocks/application/advanced-tables/

**Comment by pournasserian** [comment]
For users list, these are good examples:

https://flowbite.com/blocks/application/advanced-tables/

**Comment by abdolian** [comment]
@pournasserian how can I access to the `email confirmed`, `phone confirmed`, and `locked` properties in user list?

**Comment by abdolian** [comment]
@pournasserian In user update model `UserUpdateRequest` we don't have password property.
