### ISSUE TITLE
Components with JavaScript should be disposed correctly

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1242]
Review this document, DOM cleanup tasks during component disposal:

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#dom-cleanup-tasks-during-component-disposal
```
@page "/dom-cleanup"
@implements IAsyncDisposable
@inject IJSRuntime JS

<h1>DOM Cleanup Example</h1>

<div id="cleanupDiv"></div>

@code {
    private IJSObjectReference? module;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            module = await JS.InvokeAsync<IJSObjectReference>(
                "import", "./Components/Pages/DOMCleanup.razor.js");

            await module.InvokeVoidAsync("DOMCleanup.createObserver");
        }
    }

    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (module is not null)
        {
            await module.DisposeAsync();
        }
    }
}
```

**Comment by TheHadiAhmadi** [comment]
Yes we need to implement Dispose method.
In some components we did it, like: Tooltip and Modal.

I will work on other components.

**Comment by pournasserian** [comment]
> Yes we need to implement Dispose method. In some components we did it, like: Tooltip and Modal.
> 
> I will work on other components.

Correct, even DisposeAsync is better
