### ISSUE TITLE
Issue on using external JS file

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1293]
Assume that I have a JavaScript file in wwwroot:
**test.js**

```
<script>
    alert('loaded')
</script>
```

If I add the below tag in HTML `head` or `body` section, it won't working as expected. In SSR mode, it is fine. But, routing between interactive pages, it won't work.

If we refresh an interactive page, SSR will be loaded first. So, it will work.

This is similar question:
https://stackoverflow.com/questions/77541705/embed-javascript-in-the-blazor-component-in-net-8

**Comment by pournasserian** [comment]
@babakhani the new layout implementation is depended to this

**Comment by ParsaGachkar** [comment]
@pournasserian 
I think the `PageScript` component from this example is useful in this case. 

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0 
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#javascript-initializers

Blazor does not have this component by default but there is a detailed guide in documentation that addresses the issue and implements this solution.

**Comment by pournasserian** [comment]
> @pournasserian I think the `PageScript` component from this example is useful in this case.
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0 https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#javascript-initializers
> 
> Blazor does not have this component by default but there is a detailed guide in documentation that addresses the issue and implements this solution.

Correct, it says:

> When using Blazor's enhanced navigation feature, which allows the user to avoid reloading the entire page, page-specific JS may not be executed again as expected each time an enhanced page navigation occurs.

And then:

> To avoid this problem, we don't recommended relying on page-specific <script> elements placed outside of the layout file applied to the component. Instead, scripts should register an [afterWebStarted JS initializer](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#javascript-initializers) to perform initialization logic and use an event listener (blazor.addEventListener("enhancedload", callback)) to listen for page updates caused by enhanced navigation.

We need o define a custom Blazor component similar to the `PageScript`. 

But, we need @babakhani, @abdolian , and @TheHadiAhmadi to get their advise. Wen may do that together.

**Comment by pournasserian** [comment]
These are helpful:
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#javascript-initializers
https://github.com/MackinnonBuck/blazor-page-script

**Comment by pournasserian** [comment]
Closed by #1359
