### ISSUE TITLE
HttpContext Value cannot be null after submitting setup

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1295]
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/986d774c-da16-4c26-a641-ea56a21445e4)

**Comment by pournasserian** [comment]
@TheHadiAhmadi 
I tried to start setup and everything seems fine.

Would you explain the condition? How did you get the error?

**Comment by TheHadiAhmadi** [comment]
Sorry, I forgot to mention, it happened in my branch related to users table. 

I had some changes in that branch, I don't think it happens anymore. 

If it doesn't happen in dev, we can close the issue

**Comment by TheHadiAhmadi** [comment]
@pournasserian this is the same problem that parsa says in #1313

**Comment by pournasserian** [comment]
> @pournasserian this is the same problem that parsa says in #1313

Since we have open issue for this, I am closing this one.
