### ISSUE TITLE
Which database engine should we use in MVP version

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#13]
We should support MS SQL Server, Postgres, SQLite, MySQL, MongoDB, FileBased (JSON) repositories, etc.
- Which one should we start with? 
- Which one may have less complexity in terms of development and installation?

**Comment by MostafaTech** [comment]
In the first tech meeting, we've decided to implement repositories for NoSql databases.
The first implementations would be:
- LiteDb
- MongoDb
