### ISSUE TITLE
BasePlugin.GetUrl should replace query parameters, not append

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1304]
It should only keep pathname of a url and replace any query parameter in current url.

In Detail pages, there is an `Edit` button if we use `GetUrl` helper. when we click on it, it will return wrong URL

**Comment by TheHadiAhmadi** [comment]
@pournasserian when we want to navigate from Detail page to edit page.

Currently we don't have any detail page yet.

**Comment by pournasserian** [comment]
> @pournasserian when we want to navigate from Detail page to edit page.
> 
> Currently we don't have any detail page yet.

Since we are redesigning the plugins, I am closing this issue. Don't forget to reopen it if we face it again.
