### ISSUE TITLE
BasePlugin.NavigateBack should use `location.back` or similar methods to go to previous page

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1305]
currently it always navigates to base path of a plugin `/admin/users`.

If we navigate from Detail page to Edit page, after Submit, it should navigate to Detail page.

**Comment by pournasserian** [comment]
@TheHadiAhmadi this scenario should not happen in correct user journey. 

I am closing this issue and reopen in future required cases.
