### ISSUE TITLE
Setup Page Becomes Interactive and Causes Errors When Navigating to non root URLs

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#1313]
During the setup process, if a user navigates away from the setup page to a different URL, such as "http://localhost:5000/asd," the setup page will remain displayed but will no longer be in "noninteractive" mode. Consequently, submitting the form in this state will result in an error. To rectify this issue, the user must manually return to "http://localhost:5000/" (simply clicking the back button may not suffice; try typing in the URL or refreshing the page after clicking the back button).

**Comment by pournasserian** [comment]
duplicated #1391
