### ISSUE TITLE
Determining the usage of CSS frameworks such as Tailwind, Bootstrap, etc

### ISSUE THREAD

**Issue by abdolian** [fluentcms/FluentCMS#1315]
Determining the usage of CSS frameworks in the following cases:
- Layout files
- Builder site pages
- First load
- Need for the build command
- Ideally, not all cases can be solved within the design system

**Comment by TheHadiAhmadi** [comment]
I prefer to use tailwindcss for every sites built using FluentCMS's Site Builder, each Plugin can use any tailwindcss class. and plugins can be used in other projects.

if we make plugins css framework agnostic, adding and managing themes would be harder than creating new plugin with other css framework. (when we change theme of a page, some plugins will not work with new theme.)

Also AI knows tailwindcss well and we can use it to generate plugins. If we invent new standard for css class names (f-card, f-button, ...) It only makes learning harder.

by customizing tailwindcss using `tailwind.config.js` file, we can make it unique for sites. even we can add theme section to site builder which user can change this file using that section.

this way, Themes are just a different tailwind config which is easy to customize and easy to apply for sites.

let me know what do you think.
