### ISSUE TITLE
Develop new layout for admin panel

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1326]
Here is a good sample:
https://flowbite.com/application-ui/preview/

Also in App.razor, it is required these sections being defined by the designer (not hard-coding in server code):
`<script src="/js/flowbite.min.js"></script>`
and
```
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="AI based Headless CMS For Blazor community" />
<link rel="stylesheet" href="/_content/FluentCMS.Web.UI.Components/css/app.min.css" />
<link rel="icon" type="image/png" href="favicon.png" />
```

`before-render.js` is not correct way to implement client-side JavaScript. Delete the file.

Delete un-used page, sidebar, layout, logo components (and related components).

**Comment by TheHadiAhmadi** [comment]
Did you found any solution for #1293? 
How should we load and execute JavaScript code?
Our current layout is based on the above link, only problem is with JavaScript load after navigation

**Comment by babakhani** [comment]
Hello! You can find the FluentCMS favicon and logo files here. If you encounter any issues, feel free to reach out.

https://github.com/fluentcms/favicon

**Comment by TheHadiAhmadi** [comment]
@pournasserian I have created a repository for layout which includes static files. https://github.com/thehadiahmadi/fluentcms-layout

and here is live demo: https://fluentcms-layout.surge.sh
