### ISSUE TITLE
after navigating between layouts, if a layout has additional js script, it won't execute.

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1362]
when enhanced navigation is enabled, new javascript scripts won't register.

**Comment by pournasserian** [comment]
@TheHadiAhmadi is this resolved?

**Comment by TheHadiAhmadi** [comment]
No, if second layout has additional JavaScripts, they won't execute.

Currently in AuthLayout file we have 2 scripts which are not needed

flowbite.min.js
app.js

When this issue resolved, we can remove those scripts

**Comment by pournasserian** [comment]
There are some open issues on Blazor:

https://github.com/dotnet/aspnetcore/issues/53887
https://github.com/dotnet/aspnetcore/issues/55119
https://github.com/dotnet/aspnetcore/issues/52412

We should keep track them and revise this issue once they resolve that.

Also, in `App.razor` we should apply the client-side `window.fetch` section.

**Comment by TheHadiAhmadi** [comment]
https://github.com/dotnet/aspnetcore/issues/52273
