### ISSUE TITLE
Fix user Create/Update forms

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1370]

**Comment by pournasserian** [comment]
@TheHadiAhmadi check with the latest dev version. If issue is resolved in dev, close this PR and delete the branch.

If it is not resolved, let me know.

**Comment by TheHadiAhmadi** [comment]
@pournasserian The main problem is resolved, but after submit, it won't redirect and throws an error, I fixed it in #1372.

**Comment by pournasserian** [comment]
closed by #1422
