### ISSUE TITLE
User's list table padding issue

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1378]
<img width="860" alt="image" src="https://github.com/fluentcms/FluentCMS/assets/24959477/998cfa20-f8a2-402b-92cd-798e2ed09a20">

The card container should not have padding and table should be fit to the parent

Here is the link of design in Flowbite: font, sizes and etc. in table is not correct:
https://flowbite.com/application-ui/preview/ 
Go to Users menu.

<img width="872" alt="image" src="https://github.com/fluentcms/FluentCMS/assets/24959477/2ec6cc22-b73f-4bbe-b6ce-a04806c2ced1">

**Comment by abdolian** [comment]
@pournasserian 
- I don't have access to the codes of https://flowbite.com/application-ui/preview
The current design is based on https://flowbite.com/docs/components/tables
- Which design do you prefer? Our resources are
  - https://flowbite.com/docs/components/tables
  - https://flowbite.com/blocks/application/advanced-tables
  - https://flowbite.com/blocks/application/crud
- I've removed the padding by adding a `Padding` property on `PluginBody` component. you can see on the branch.

**Comment by abdolian** [comment]
@babakhani
