### ISSUE TITLE
Test InteractiveServer render mode in different states

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#1449]
1 - Interactive Plugin + Simple page
2 - Interactive Plugin + Form page
3 - Static Plugin + Interactive component
4 - Static Plugin + Interactive component with form

**Comment by pournasserian** [comment]
@TheHadiAhmadi do we need this investigation? Did we complete that?

**Comment by TheHadiAhmadi** [comment]
No we don't need.
