### ISSUE TITLE
Problem with PhoneNumber  property in UpdateCurrentAsync api

### ISSUE THREAD

**Issue by abdolian** [fluentcms/FluentCMS#1498]
PhoneNumber is empty and the API returns an error.

```cs
await GetApiClient<AccountClient>().UpdateCurrentAsync(ProfileModel);
```
![image](https://github.com/fluentcms/FluentCMS/assets/43126626/57c88e78-bca2-4d1d-9e86-6642618bb72a)

**Comment by pournasserian** [comment]
@abdolian we are doing the same in `UserController`. Mention your branch.

**Comment by abdolian** [comment]
@pournasserian 1401-review-auth-plugin-and-apply-new-input-components-changes

**Comment by pournasserian** [comment]
related to https://github.com/fluentcms/FluentCMS/issues/1504
