### ISSUE TITLE
404 in calling unknown call for Flowbite js

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1507]
Ass you see in the below screenshot, when we run project, there is a js call:
<img width="401" alt="image" src="https://github.com/fluentcms/FluentCMS/assets/24959477/8e00574d-f8d7-436d-83a8-335e42a97ecb">
What is the reason? We don't call this file anywhere.

**Comment by TheHadiAhmadi** [comment]
This is because of sourcemap.

I will work on it
