### ISSUE TITLE
In form action component, `Submit` button should be the first, then `Cancel`

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1539]
Here is the sample Flowbite form:

<img width="500" alt="image" src="https://github.com/fluentcms/FluentCMS/assets/24959477/5e515bd6-ecd2-4a08-86e6-6172d0c73b3e">

@TheHadiAhmadi what do you thin? Should the cancel button be the first or second?

**Comment by TheHadiAhmadi** [comment]
I prefer this order if we move buttons to the right. Otherwise we can move submit to the left of cancel.
