### ISSUE TITLE
Add breadcrumb to admin layout

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1578]
Similar to Flowbite here:
https://flowbite.com/application-ui/preview/
<img width="901" alt="image" src="https://github.com/fluentcms/FluentCMS/assets/24959477/f674fc68-4506-42d0-aaf5-f0bc7d55454c">

**Comment by TheHadiAhmadi** [comment]
@pournasserian to do this task, I need to have access to current route and it's parents data in layout as Scriban variables.

```
[ 
    { Href: "string", Title: "string", Active: true },
    { Href: "string", Title: "string", Active: true },
    ...
 ]
```

for above example this list should be something similar to:
```
[
    { Href: "/", Title: "Home", Active: true },
    { Href: "/users", Title: "Users", Active: true },
    { Href: "/users", Title: "List", Active: false },
]
```
