### ISSUE TITLE
UI enhancements for datatable, header, etc.

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1718]
- [x] in all datatables, action column should have min length zero
- [ ] #1744
- [x] folders and files should be shown in one table (first folders, then files)
- [x] create/update folder should be done in modal
- [x] create/update file should be done in modal
- [ ] #1743
- [x] add download button to file
- [x] add a row in datatable (first row) for linking to parent folder
- [x] develop new button components being used in page headers and action sections in datatables

**Comment by TheHadiAhmadi** [comment]
All of these tasks are done except 2 task which has dedicated issue
