### ISSUE TITLE
Review and refactor ContentType and Content Management plugins

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1938]
- After saving a content Which has Guid field type (SingleFile):

```
Unknown: An error occurred while serializing the Data property of class FluentCMS.Entities.Content: GuidSerializer cannot serialize a Guid when GuidRepresentation is Unspecified.
```

- If we add new field to ContentType, Content list page doesn't work. Because all previous contents doesn't have value for the new field.

- ContentType fields should have validation: Name should not be empty and Name should be unique
- DefaultValue doesn't work in Date field type

**Comment by TheHadiAhmadi** [comment]
boolean's Switch type in table doesn't work
