### ISSUE TITLE
Refactor and review Page Management plugin

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1940]
- Path should have only one segment (/a/b is not valid)
- Parent Page id should not be the same page's id
- Path should be unique
- Path should be stored as the user entered, but when we want to check the uniqueness, it should be case insensitive  
- Null parent page is not working
- Think of parent page deletion

**Comment by TheHadiAhmadi** [comment]
for number 3, I think (Parent Page + Path) should be unique not only path
