### ISSUE TITLE
UI Mess in Header on Mobile Size

### ISSUE THREAD

**Issue by babakhani** [fluentcms/FluentCMS#2085]
Steps to Reproduce:

Open the website on a mobile device or use the mobile view in the site builder toolbar.

Navigate to the homepage.

Observe the header section.

Expected Behavior:
The header should be neatly organized with clear spacing between elements, ensuring readability and a clean appearance.

Actual Behavior:
The header is cluttered, with text overlapping and elements not properly aligned.

Screenshots:

![Screenshot 1403-07-09 at 21 00 56](https://github.com/user-attachments/assets/ef49a124-d044-4e14-a5d5-f86a46ac4c35)

**Comment by TheHadiAhmadi** [comment]
https://github.com/fluentcms/FluentCMS/pull/2268
![image](https://github.com/user-attachments/assets/90658b2e-9db8-48d5-ae32-9149fecf4938)
