### ISSUE TITLE
Change object model design to enable Rdbms

### ISSUE THREAD

**Issue by BigHoss** [fluentcms/FluentCMS#2161]
these adaptations are necessary for these models to be used with a rdbms

## GlobalSettings

Change ```FileUpload``` to be nullable (as it is null in the setup process)
Change ```SuperAdmins``` to *List* or *Array* as *IEnumerable* is not mappable

![image](https://github.com/user-attachments/assets/5c0bed6a-0ae7-4ca5-b815-ef03edf529f4)

## PluginDefinition

Change ```Category``` to be nullable (as it is null in the template used)

![image](https://github.com/user-attachments/assets/25d65fce-d57e-4bfc-be7b-df9bd8a5884b)

**Comment by pournasserian** [comment]
@BigHoss resolved! thanks
