### ISSUE TITLE
File / Folder issues

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#2217]
1 -> Folder Delete doesn't work if it has other file/folders inside of it.
2 -> File Rename and File Move is not implemented.
3 -> Files uploaded by setup, doesn't have ContentType

**Comment by NightOwls0** [comment]
@pournasserian There are more issues related to file/folder

1 - for getting FileUploadConfig from GlobalSettings, Api returns null (We need to fill settings during setup)
2 - rename folder doesn't check validation if a folder renamed to name of an existing folder. (Also for files)
3 - It would be better to have an api to get list of parent folders for Breadcrumbs based on a FolderId (List<FolderDetailResponse>)
4 - currently It is possible to move a folder to it self (`ApiClient.Folder.MoveAsync({Id = "ID_OF_FOLDER_TEST", ParentId="ID_OF_FOLDER_TEST"}`) (I've disabled this in frontend)
