### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by itiwant** [fluentcms/FluentCMS#2279]
I can't Installation this project by follow your guidline
![image](https://github.com/user-attachments/assets/3bc3b15a-ef55-465b-b7b0-9d064f8cdbda)

**Comment by pournasserian** [comment]
@itiwant it seems that you have setup the project and created the db. It will automatically install all required records and configure the appsettings.json file. After setup, the api key in appsettings.json will be added.

The above exception may happen if you already have the db initialized, but the api key is not valid.

Would you explain more about your steps to reproduce that?

Which db are you using?

**Comment by itiwant** [comment]
Hi @pournasserian, I downloaded the code and then opened it with visual studio. When I ran it, the setup page interface appeared. Then I entered the password and got an error. Then I ran it again by going to the `FluentCMS/src/FluentCMS/ `folder and running `dotnet run` and got the above error.

**Comment by pournasserian** [comment]
@itiwant thanks. You are right. When you want to start the setup process, nothing exists on DB. In the process of setup, we need to create the admin user. If the password or username does not meet the requirements, it will raise exception and the setup process won't be completed and you should delete the db and start again.

I will add the validation in setup to avoid that. See this:
https://github.com/fluentcms/FluentCMS/issues/2287

**Comment by flibbertigibbet-uk** [comment]
As a new user today I am happy to report that from VS2022 I used the clone from repository function and FluentCMS dowenloaded, built and run successfully from F5 within 3 minutes. I accepted the masked default password and Google Chrome saved that for me.

I am now blundering around the demo site trying to understand the concepts, got the Admin/Live UI flip idea but 20 minutes in page design remains a mystery. The short screen capture video on the GitHub project dashboard hints at the workflow, I shall use that as my intro tutorial.

A 10 minute explainer video on YouTube would help.

**Comment by pournasserian** [comment]
> As a new user today I am happy to report that from VS2022 I used the clone from repository function and FluentCMS dowenloaded, built and run successfully from F5 within 3 minutes. I accepted the masked default password and Google Chrome saved that for me.
> 
> I am now blundering around the demo site trying to understand the concepts, got the Admin/Live UI flip idea but 20 minutes in page design remains a mystery. The short screen capture video on the GitHub project dashboard hints at the workflow, I shall use that as my intro tutorial.
> 
> A 10 minute explainer video on YouTube would help.

We need to start writing documentation section ASAP! 

I am closing this issue.

Thanks
