### ISSUE TITLE
Develop primary Blazor components

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#235]

**Comment by TheHadiAhmadi** [comment]
Adding `Alert`, `AlertContainer` and `Icon` components.

Editing `Button`, `Card`, `DropdownMenu`, `DropdownButton` and `EditPage` components.

**Comment by TheHadiAhmadi** [comment]
Added `Checkbox` and `Textarea` components.


Also added "KitchenSink" page
