### ISSUE TITLE
Implement LiteDb Integration

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#25]

**Comment by pournasserian** [comment]
@ParsaGachkar @MostafaTech review the below resources:
- https://github.com/fluxera/Fluxera.Repository
- https://github.com/quicksln/LiteDB.Identity
- https://github.com/fabian-blum/AspNetCore.Identity.LiteDB
- https://github.com/devinSpitz/LiteDB.Identity.Async
- https://github.com/mwkldeveloper/AspNetCore.Identity.LiteDB

**Comment by ParsaGachkar** [comment]
> @ParsaGachkar @MostafaTech review the below resources:
> 
> * https://github.com/fluxera/Fluxera.Repository
> * https://github.com/quicksln/LiteDB.Identity
> * https://github.com/fabian-blum/AspNetCore.Identity.LiteDB
> * https://github.com/devinSpitz/LiteDB.Identity.Async
> * https://github.com/mwkldeveloper/AspNetCore.Identity.LiteDB

I Like Fluxera Implementation we could use it. @MostafaTech @pournasserian
