### ISSUE TITLE
Should we change the `Section` component's name to something else?

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#252]
Blazor has built-in `SectionOutlet` and `SectionContent` features. 

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/sections?view=aspnetcore-8.0

In order to avoid confusion, it is better to change `Section` component's name to something else (PluginContainer, Fragment, Segment, Content, etc.).

**Comment by TheHadiAhmadi** [comment]
What do you think about `Slot`, `Shortcode` or `FluentSection`?

**Comment by abdolian** [comment]
`Section` component should be renamed to`PluginSection`
