### ISSUE TITLE
Replace Flowbite JS with Native Blazor Features

### ISSUE THREAD

**Issue by babakhani** [fluentcms/FluentCMS#292]
I propose replacing Flowbite JS with native Blazor features to improve the performance and maintainability of the project. The reasons for my proposal are:

Code Consistency: Using standard .NET C# to manage components instead of JavaScript will make the code more consistent and easier to maintain.

Maintainability: Flowbite JS requires additional maintenance and updates. By using native Blazor features, we can simplify the maintenance of the project.

The steps to replace Flowbite JS with native Blazor features are:

Identify the Flowbite JS components used in the project.
Replace each Flowbite JS component with its native Blazor equivalent.
Remove the Flowbite JS library from the project.

Please let me know if you have any questions or concerns regarding this proposal.

**Comment by TheHadiAhmadi** [comment]
@babakhani 
Yes it would be great. I am agree

**Comment by babakhani** [comment]
https://github.com/fluentcms/FluentCMS/issues/373
