### ISSUE TITLE
Text HTML refactor 

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#306]
- [x] Add `EditForm` to `TextHtmlEditPlugin.razor`
- [x] Fix double call on `TextHtmlEditPlugin`'s `Initialization`

**Comment by ParsaGachkar** [comment]
@pournasserian there are multiple solutions to avoid double call for `OnInitialized`

- First one i noticed at Microsoft's doc is to cache the data in our client service [Stateful reconnection after prerendering](https://learn.microsoft.com/en-gb/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#stateful-reconnection-after-prerendering) so it prevents second Api call at client level but duplicate code execution still remains. 
- We can always disable prerendering this is a feasible solution for admin panel as we don't really need prerendering at admin panel almost all `CSR` frameworks Angular, React, Vue don't have `SSR` enabled and yet they work perfectly fine as private access Admin Panels that don't need `SSR`. but it's not good for Crawler Bots and `SEO` so our Public Pages absolutely need `SSR`.
- Another solution is to check whether the response header has been sent to the client. if it's not, server is still prerendering else it's running at browser [ IHttpContextAccessor.HttpContext.Response.HasStarted](https://stackoverflow.com/a/60589934/9671940). as you can see this is more like a hack than a proper solution. check the comments on the solution some people believe that this is not a good solution and there is not guaranty that this will not be changed in future. some suggest just using `OnAfterRender(bool isFirstRender)` and ignore `OnInitialized` as it is guaranteed by the signature.

**Comment by pournasserian** [comment]
@ParsaGachkar please implement based on the third solution. Then we will review that.

**Comment by ParsaGachkar** [comment]
there was a problem after removing the second call by checking `IHttpContextAccessor.HttpContext.Response.HasStarted` all values that were being set in `OnInitialized` were `null`! so, i took a hybrid approach of solutions 1 and 3! 

- add an `OnPreRendering` method definition to avoid double calling of our `db` logic
- cache values after `OnPreRendering` 
- restore values from cache at client-side `OnInitialized` call
- define an attribute `MemoryCachedValueAttribute` to ease the process (avoid storing and restoring all properties of Component)
