### ISSUE TITLE
Implement a sample ```API Controller```  as a guideline

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#31]
The API should support:
- CRUD
- Search/filtering support

Method responses should have a generic details like:
- Duration
- Exception
- Data
- TraceId

**Comment by MostafaTech** [comment]
I suggest to design the global response model like this:
```json
{
    data: any,
    error: string
}
```
and for other debugging and tracing we use Http Response Headers. for example:
```
XFC-TRACEID=
XFC-DURATION=
```
and the benefits are:
1 - Only advanced users would use these values.
2- These values simply can be added to reponse object using middleware.
