### ISSUE TITLE
Namespace enhancement suggestion 

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#34]
Common highly used basic classes should be in the root namespace.

Isn't it better to have ```FluentCMS``` instead of ```FluentCMS.Core.Entities``` for ```IEntity```?

**Comment by MostafaTech** [comment]
Are you suggest to remove `Core` from Entities namespace?

**Comment by pournasserian** [comment]
> Are you suggesting to remove `Core` from Entities namespace?

Correct, `FluentCMS` may be enough, not sure...

**Comment by MostafaTech** [comment]
It's done.
