### ISSUE TITLE
Configure ```appsettings.json``` from separate files in ```Config``` folder

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#35]

**Comment by MostafaTech** [comment]
Actually I'm not agree to put appsettings.json files into a subdirectory. Because people always expect to find them in root dir like any other project. And also i don't see any benefits to dedicate a directory to separate them from other project files in the root level.

**Comment by pournasserian** [comment]
> Actually I'm not agree to put appsettings.json files into a subdirectory. Because people always expect to find them in root dir like any other project. And also i don't see any benefits to dedicate a directory to separate them from other project files in the root level.

We may postpone this and discuss about that later.

**Comment by MostafaTech** [comment]
@pournasserian 
I think we need some kind of `postponed` label to set on these type of issues.
