### ISSUE TITLE
Feasibility study for dynamic Sorting, Filtering, Ordering, and Pagination in API Controller

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#43]
https://github.com/enisn/AutoFilterer
https://github.com/Biarity/Sieve 
https://blog.zhaytam.com/2020/05/17/dynamic-sorting-filtering-csharp/ 
https://github.com/gabihodoroaga/blog-dynamic-filters 
https://medium.com/@rashad_m/mastering-filtering-and-pagination-in-asp-net-core-and-react-js-part-1-591b10a65993 
https://www.strathweb.com/2018/01/easy-way-to-create-a-c-lambda-expression-from-a-string-with-roslyn/

**Comment by ParsaGachkar** [comment]
@pournasserian @MostafaTech @SeyedMohsenMousaviMoghaddam review https://github.com/enisn/AutoFilterer

**Comment by pournasserian** [comment]
```
public class FilterParams
{

}

public class SortParams
{
    public string FieldName { get; set; } = string.Empty;
    public bool Ascending { get; set; } = true;
}
public class PaginationParams
{
    public int Number { get; set; } = 1;
    public int Size { get; set; } = 20;
}

public class SearchParams
{
}

public class Query
{
    public List<SortParams>? Sorts { get; set; }
    public PaginationParams? Paging { get; set; }
    public FilterParams? Filter { get; set; }
    public SortParams? Sort { get; set; }
}

```

**Comment by ParsaGachkar** [comment]
#91 it needs to be implemented at Repository too not just API these could be useful in our services!
