### ISSUE TITLE
Which version of .net to use? 7 or 8?

### ISSUE THREAD

**Issue by MostafaTech** [fluentcms/FluentCMS#49]
Dotnet 8 will be the next LTS version and it scheduled to be released versy soon:
> .NET 8 is the next LTS version of the .NET framework (scheduled for November 2023), a powerful and versatile platform for building modern applications. As a Long Term Support (LTS) version it will updated for the next 3 years.

And dotnet 7 is not an LTS version. So, should we move the project to version 8 (its rc now)?

**Comment by pournasserian** [comment]
> Dotnet 8 will be the next LTS version and it scheduled to be released versy soon:
> 
> > .NET 8 is the next LTS version of the .NET framework (scheduled for November 2023), a powerful and versatile platform for building modern applications. As a Long Term Support (LTS) version it will updated for the next 3 years.
> 
> And dotnet 7 is not an LTS version. So, should we move the project to version 8 (its rc now)?

Since version 8 has major changes in Blazor Server App, we should migrate to 8 as soon as we start developing Admin Blazor App (Admin UI).

**Comment by MostafaTech** [comment]
Project migrated to version 8 of .net
