### ISSUE TITLE
Specify coding convetions

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#5]
Here is the latest Microsoft's guideline for coding styles:
- https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names
- https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

Should we rely on that, or there is another popular coding style?

**Comment by MostafaTech** [comment]
These guides added to CONTRIBUTING.md document in coding conventions section
