### ISSUE TITLE
Investigate routing solutions in Blazor

### ISSUE THREAD

**Issue by abdolian** [fluentcms/FluentCMS#718]
- Authentication 
- Authorization 
- Dynamic Route Definition
- Routing based on names

**Comment by abdolian** [comment]
- https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0
- https://www.pragimtech.com/blog/blazor/authorization-in-blazor
- https://docs.abp.io/en/abp/latest/UI/Blazor/Navigation-Menu

**Comment by pournasserian** [comment]
@abdolian I have already implemented those tasks. Please set a meeting to discuss.
