### ISSUE TITLE
Add simple CRUD for Site

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#73]
**Site**: AuditEntity

- Name
- Description
- Urls: List<string> (www.x.com, x.com, etc.)
- Pages: List<Page Id> (PageId is Id for Page class)
- DefaultPage: PageId
- Administrator: RoleId

Route pattern: /admin/sites/
- add
- update
- list
- view

# todo:
- [x] UI
  - [x] List
  - [x] Create
  - [x] Update
  - [x] Delete

**Comment by ParsaGachkar** [comment]
- [ ] Entity
- [ ] Repository
- [ ] Service
- [ ] Commands & Queries
- [ ] UI
