### ISSUE TITLE
accidentally clicking on outside of modals in CRUD results in data loss.

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#753]
accidentally clicking on outside of modals in CRUD results in closing of modal with data loss.

we can prevent this with a confirmation from user to close the modal / being able to disable the behavior of dismissing when clicking away from it. 

@babakhani what do you think?

**Comment by abdolian** [comment]
@ParsaGachkar I'll add a `static` property to prevent unwanted closing
