### ISSUE TITLE
`ContentType` functionality

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#766]

**Comment by ParsaGachkar** [comment]
@abdolian our `ContentType` update form is broken we have to set one of `Model` and `EditContext` parameter (we can't set both eaither) in a single `EditFrom` this would result in an exception! Our form functions correctly if we pass the Model on initialization but we get error when we pass the Model async (after initialization).
```
InvalidOperationException: EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.
```

**Comment by TheHadiAhmadi** [comment]
@ParsaGachkar Fixed!
