### ISSUE TITLE
Adding a field should not modify the `ContentType` unless i apply changes for `ContentType` 

### ISSUE THREAD

**Issue by ParsaGachkar** [fluentcms/FluentCMS#772]
I know this might be out of context for our MVP but I'm expecting that `ContentType` changes to get disposed if I'm clicking on `Cancel` instead of `Save`

**Comment by TheHadiAhmadi** [comment]
@ParsaGachkar Yes it is possible to wait until user clicks `Save`. then make requests to add Fields.

or support `fields` field for `ContentTypeUpdateRequest` model. (remove SetField and DeleteField apis)

**Comment by ParsaGachkar** [comment]
I think fields should be a part of the Create / Update request! Not a separate operation.
