### ISSUE TITLE
Issue with JSInterop after new changes

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#815]
There is no issue when user works with system, only occurs in tests.
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/1729aa02-a12d-417d-862f-9a8471301149)

**Comment by TheHadiAhmadi** [comment]
#816 You can see problem by running tests in this branch

**Comment by ParsaGachkar** [comment]
```
  Admin Panel
    √ Check Navbar (11856ms)
    √ The sidebar should exist. (144ms)
    √ The theme button should change theme when clicked. (5254ms)
    √ Should navigate to home page if clicked logo or Home link (247ms)
    1) Clicking on links should redirect to correct pages


  4 passing (22s)
  1 failing

  1) Admin Panel
       Clicking on links should redirect to correct pages:
     AssertionError: Timed out retrying after 4000ms: expected '<a.group>' to have attribute 'target'
      at Context.eval (webpack://fluentcms.e2e/./cypress/commands/admin-layout.js:12:38)
```

Tast-case is expecting our doc link to have an `_blank` target bud looks like our `SidebarItem` does not support it

![image](https://github.com/fluentcms/FluentCMS/assets/33961204/a2e04e30-3780-4f63-b577-5bc1ea8393ca)

all other tests are passing!
