### ISSUE TITLE
Review and select `render` mode in Blazor apps for admin UI 

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#84]
https://www.reddit.com/r/Blazor/comments/11w0xgz/those_using_blazor_server_are_you_using/
https://stackoverflow.com/questions/66503874/blazor-rendering-content-twice
https://stackoverflow.com/questions/58075628/why-are-blazor-lifecycle-methods-getting-executed-twice

**Comment by ParsaGachkar** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#render-modes

We need to discuss this.

Our Authentication/Authorization highly depends on this decision. especially our SSR status

We are planning to be a complete CMS so SEO and SSR are crucial.

Looks like a good approach to persist tokens in server and client is to use a [OIDC](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app)

**Comment by pournasserian** [comment]
Resolved
