### ISSUE TITLE
Code cleanup in Razor components

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#913]
The best practice in Razor files is to split the lines when they are too long. But, we are splitting them even if they are very short. Here is an example in CardFooter.razor:

```
@inherits BaseComponent

@namespace FluentCMS.Web.UI.Components

<div @attributes="AdditionalAttributes"
     class="@this.GetClasses()">
    @ChildContent
</div>

```

It should be:

```
@inherits BaseComponent

@namespace FluentCMS.Web.UI.Components

<div @attributes="AdditionalAttributes" class="@this.GetClasses()">
    @ChildContent
</div>

```

**Comment by abdolian** [comment]
Because of the limitations that exist for the Blazor formatter, it cannot be limited to the number of characters. We agreed to break more than one.
do you want a new agreement?
