### ISSUE TITLE
Use separate file for enums in Blazor components

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#915]
In Button.razor.cs, we have the below code:
```
namespace FluentCMS.Web.UI.Components;
public enum ButtonSize
{
    Default,
    Small,
    Medium,
    Large
}

public enum ButtonType
{
    Button,
    Submit,
    Reset
}
```
Each enum should be in a separate file. So, we won't have the file (Button.razor.cs). And then, we should add two files (ButtonSize.cs and ButtonType).

Or, we can put all the enums in a single file.

**The .razor.cs files should ONLY contains the code-behind for each individual .razor component (not any other classes, enums, helpers, etc.)**

**Comment by abdolian** [comment]
I agree with you and I have done this in PR #909. Check it, please.

**Comment by abdolian** [comment]
@pournasserian check the latest dev branch.

**Comment by pournasserian** [comment]
> Each enum should be in a separate file.

@abdolian I don't see separate file for enums.

**Comment by abdolian** [comment]
@pournasserian I agree with the separating files like ButtonSize.cs and ButtonType.cs.
