### ISSUE TITLE
Content-Type API requirments

### ISSUE THREAD

**Issue by babakhani** [fluentcms/FluentCMS#944]
- Text
  - Name
  - Type
    - Short
    - Long
  - Default value
  - RegExp pattern
  - Required
  - Unique
  - Maximum length
  - Minimum length
  - Private 
  - Localization

- Email
  - Name
  - Default value
  - Required
  - Unique
  - Maximum length
  - Minimum length
  - Private 
  - Localization

- Rich Text/Markdown/Password
  - Name
  - Default value
  - Required
  - Maximum length
  - Minimum length
  - Private 
  - Localization

- Number 
  - Name
  - Number format
    - Integer
    - Big Integer
    - Decimal
    - Float
  - Default value
  - Required
  - Unique
  - Maximum value
  - Minimum value
  - Private 
  - Localization
  
- Enumeration 
  - Name
  - Values (Array of string)
  - Default value
  - Name override for GraphQL (String)
  - Required
  - Private 
  - Localization

- Date
  - Name
  - Type
    - Date
    - DateTime
    - Time
  - Default value
  - Required
  - Unique
  - Private 

- Media
  - Name
  - Type
    - Multiple
    - Single
  - Select allowed types of media (Array of string)
  - Required
  - Private 
  - Localization

- Boolean 
  - Name
  - Default value
  - Required
  - Private 
  - Localization

**Comment by ParsaGachkar** [comment]
I'm not sure about  Maximum length & Minimum length for Email field doesn't it add unnecessary confusion? 

Localization for email doesn't really make sense too! i get it that we can have multiple emails for multiple locales but do we really need it?

wouldn't Dictionary of String/int or String/String be much better for enumeration list values?

looks like we have duplicate text field definition!

I'm not sure about  Maximum length & Minimum length for Markdown/RichText too as they can be really long especially if they contain complicated svg or base64 data.

**Comment by abdolian** [comment]
Maximum/Minimum length and Localization for Email/Markdown/RichText are optional and they are presented by Strapi.
